export enum GameEvent {
    TILE_CLICKED = "TILE_CLICKED",

    CLUSTER_DESTROYED = "CLUSTER_DESTROYED",
    BOARD_UPDATED = "BOARD_UPDATED",

    SCORE_CHANGED = "SCORE_CHANGED",
    MOVES_CHANGED = "MOVES_CHANGED",

    GAME_WON = "GAME_WON",
    GAME_LOST = "GAME_LOST"
}